version: '3'
services:
  frontend:
    # image: mlb-weather-fe
    build:
      context: .
      dockerfile: Dockerfile-prod
    image: mlb-frontend-prod
    environment:
      NODE_ENV: production
    ports:
      - 80:80

networks:
  default:
    external:
      name: mlbw-network