version: '3'

services:
  frontend:
    # image: mlb-weather-fe
    build: .
    environment:
      NODE_ENV: production
    ports:
      - 3000:3000


networks:
  default:
    external:
      name: mlbw-network