version: '3'

services:
  backend:
    image: mlb-weather
    build: .
    environment:
      NODE_ENV: production
    ports:
      - 3001:3001

networks:
  default:
    external:
      name: mlbw-network